.PHONY: all pack clean run profile help

@all: calc_qt.py
	python3 calc_qt.py
@pack:
	#todo
@clean:
	cd .. && cd src && rmdir __pycache__ /s /q
@run:
	#
@profile: profiling.py
	python3 profiling.py
help:
	echo "Run make with: pack, clean, run, profile, help"

